name: DMP 2024 Project Template	
description: List a new project for Dedicated Mentoring Program (DMP) 2024 
title: "[DMP 2024]: "
labels: ["DMP 2024"]
body:
  - type: textarea
    id: ticket-description
    validations:
      required: true
    attributes:
      label: Ticket Contents
      value: |
        ## Description
        ekShop marketplace is a robust and adaptable eCommerce platform that is free and open-source. It is designed to cater to the needs of any potential entrepreneur who wants to set up an online store quickly and efficiently. With its customizable and configurable features, ekShop can be tailored to suit your specific requirements.
        
        **Enhancement Scope**
        1. UI/UX design can be enhanced and updated.
        2. Implementation of data analytics tools and analytical dashboard. 


  - type: textarea
    id: ticket-goals
    validations:
      required: true
    attributes:
      label: Goals & Mid-Point Milestone
      value: |
        ## Goals for a ekshop:
        - [ ] User-Friendly Interface: Develop an intuitive and user-friendly design for easy template creation.
        - [ ] Data Analysis: Development of analytical dashboard and information mediator
        
  - type: textarea
    id: ticket-setup
    attributes:
      label: Setup/Installation 
      value: |
        Installations guidelines:
        - https://github.com/a2i-code-For-Govstack/nise3-skill-and-certification/blob/master/README.md

  - type: textarea
    id: ticket-expected-outcome
    attributes:
      label: Expected Outcome
      value: |
        Implementation of data analytic tools and analytical dashboard and implementation of information mediator

  - type: textarea
    id: ticket-acceptance-criteria
    attributes:
      label: Acceptance Criteria
      value: |
        Better Ui/ Ux and analytical dashboard

  - type: textarea
    id: ticket-implementation-details
    validations:
      required: true
    attributes:
      label: Implementation Details
      value: |
        The project will be developed using Laravel framework. Specific tasks include:
        - Enhancing UI/UX design.
        - Implementation of analytical dashboard
        - implementation of information mediator

  - type: textarea
    id: ticket-mockups
    attributes:
      label: Mockups/Wireframes
      value: |
        https://github.com/a2i-code-For-Govstack/ekshop/blob/master/README.md

  - type: input
    id: ticket-product
    attributes:
      label: Product Name
      placeholder: Ekshop 
    validations:
      required: true

  - type: textarea
    id: ticket-organisation
    attributes:
      label: Organisation Name
      description: Enter Organisation Name
      value: a2i
    validations:
      required: true

  - type: textarea
    id: ticket-governance-domain
    attributes:
      label: Domain
      description: Enter the domain of the project
      value: https://dpg.ekshop.gov.bd
    validations:
      required: true

  - type: textarea
    id: ticket-technical-skills-required
    attributes:
      label: Tech Skills Needed
      value: Laravel, API , PHP , Data Analysis
    validations:
      required: true
